### ISSUE TITLE
Send Notification in Non English language like Arabic and Persian dose not work

### ISSUE THREAD

**Issue by sonsy-soft** [tpeczek/Demo.AspNetCore.PushNotifications#15] opened 2021-08-05 04:26 UTC
I ran the  Demo.AspNetCore.PushNotifications Project but it didn't work with Non English language?
please help me
For Example 
سلام ->Title
message ->  برای آزمایش

**Comment by tpeczek** [comment] 2021-08-05 13:12
Hi @sonsy-soft ,

I'm assuming that by "non English" you mean languages which characters require more than one code units when encoding with UTF-8 (I'm actively using this with Slavic languages and I haven't experienced any issues).

If that's the case, than indeed there can be a bug somewhere - less likely in actual library handling push notifications, more likely in demo code around it.

Unfortunatelly I wont be able to sit down to it sooner than around 23rd-24th of August.

**Comment by sonsy-soft** [comment] 2021-08-05 16:07
dear tpeczek,
you can test the solution by the sample I wrote above.
سلام -> for title
این برای آزمایش است - message body

thanks

**Comment by tpeczek** [comment] 2021-08-23 19:28
Hi @sonsy-soft,

I've finally had time to take a look at this one and I've concluded that everything works as designed. You can safely use the data you desire in message body (the example provided by you will also work). The reason you are seeing failure is the value for Topic - this one is constrained by the protocol.

First of all, Topic is being transferred as HTTP header which creates initial set of characters limitation. Further, the Web Push Protocol itself constraints Topic to be no more than 32 characters from the URL and a filename-safe Base 64 alphabet.

I believe the biggest confusion here is what Topic is. It's not a title of the message. It’s an optional token which is used to correlate push messages sent to the same subscription and does not convey any other semantics. It's never displayed to the user. What it allows is replacing message which has been stored by the push service and not yet delivered to the user.

**Closed as completed** 2021-08-29 19:33 UTC
